# Project identification
sonar.projectKey=NextStep
sonar.projectName=NextStep
sonar.projectVersion=1.0

# Path to the source directories
sonar.sources=.

# Exclusions
sonar.exclusions=**/node_modules/**, **/bin/**, **/obj/**, **/dist/**, **/wwwroot/**, **/*.spec.ts, **/tests/**, **/Migrations/**

# Specific configuration for languages
# C# (Backend)
sonar.dotnet.excludeTestProjects=true

# JavaScript/TypeScript (Frontend)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.tsconfigPath=frontend/tsconfig.json

# Encoding of the source code
sonar.sourceEncoding=UTF-8
