INSERT INTO skill_keyword (mot, categorie) VALUES
('JavaScript', 'Technique'), ('TypeScript', 'Technique'), ('Python', 'Technique'),
('Java', 'Technique'), ('C#', 'Technique'), ('C++', 'Technique'),
('PHP', 'Technique'), ('Go', 'Technique'), ('Rust', 'Technique'),
('Ruby', 'Technique'), ('Swift', 'Technique'), ('Kotlin', 'Technique'),
('Angular', 'Framework'), ('React', 'Framework'), ('Vue.js', 'Framework'),
('Next.js', 'Framework'), ('Node.js', 'Framework'), ('Express.js', 'Framework'),
('NestJS', 'Framework'), ('Spring Boot', 'Framework'), ('.NET', 'Framework'),
('ASP.NET Core', 'Framework'), ('Django', 'Framework'), ('Flask', 'Framework'),
('FastAPI', 'Framework'), ('Laravel', 'Framework'), ('Ruby on Rails', 'Framework'),
('PostgreSQL', 'Base de données'), ('MySQL', 'Base de données'), ('MongoDB', 'Base de données'),
('Redis', 'Base de données'), ('SQLite', 'Base de données'), ('SQL Server', 'Base de données'),
('Oracle', 'Base de données'), ('Firebase', 'Base de données'),
('Docker', 'DevOps'), ('Kubernetes', 'DevOps'), ('Jenkins', 'DevOps'),
('GitHub Actions', 'DevOps'), ('GitLab CI/CD', 'DevOps'), ('Terraform', 'DevOps'), ('Ansible', 'DevOps'),
('AWS', 'Cloud'), ('Azure', 'Cloud'), ('Google Cloud', 'Cloud'),
('Git', 'Outil'), ('Linux', 'Outil'), ('Nginx', 'Outil'), ('Jira', 'Outil'),
('Figma', 'Outil'), ('Postman', 'Outil'),
('HTML', 'Technique'), ('CSS', 'Technique'), ('SASS/SCSS', 'Technique'),
('Tailwind CSS', 'Technique'), ('Bootstrap', 'Technique'),
('REST API', 'Technique'), ('GraphQL', 'Technique'), ('WebSocket', 'Technique'),
('Microservices', 'Architecture'), ('Design Patterns', 'Architecture'),
('Clean Architecture', 'Architecture'), ('SOLID', 'Architecture'),
('Agile/Scrum', 'Méthodologie'), ('Kanban', 'Méthodologie'),
('TDD', 'Méthodologie'), ('CI/CD', 'Méthodologie'),
('Machine Learning', 'IA'), ('Deep Learning', 'IA'), ('NLP', 'IA'),
('TensorFlow', 'IA'), ('PyTorch', 'IA'), ('scikit-learn', 'IA'),
('Communication', 'Soft Skill'), ('Travail en équipe', 'Soft Skill'),
('Leadership', 'Soft Skill'), ('Résolution de problèmes', 'Soft Skill'),
('Gestion du temps', 'Soft Skill'), ('Adaptabilité', 'Soft Skill'), ('Créativité', 'Soft Skill'),
('RxJS', 'Technique'), ('Jest', 'Technique'), ('Cypress', 'Technique'),
('Selenium', 'Technique'), ('Pandas', 'Technique'), ('NumPy', 'Technique'),
('Power BI', 'Outil'), ('Tableau', 'Outil'), ('Excel', 'Outil'),
('UML', 'Méthodologie'), ('Merise', 'Méthodologie'),
('Hadoop', 'Big Data'), ('Spark', 'Big Data'), ('Kafka', 'Big Data'),
('ElasticSearch', 'Big Data'), ('Dart', 'Technique'), ('Flutter', 'Framework'),

-- Programming Languages (additional)
('Scala', 'Technique'), ('R', 'Technique'), ('MATLAB', 'Technique'),
('Shell/Bash', 'Technique'), ('PowerShell', 'Technique'), ('Lua', 'Technique'),
('Elixir', 'Technique'), ('Julia', 'Technique'), ('Solidity', 'Technique'),

-- UI / Interface
('Material UI', 'Framework'), ('Chakra UI', 'Framework'), ('Radix UI', 'Framework'),
('Shadcn/ui', 'Framework'), ('Storybook', 'Outil'),
('Framer Motion', 'Technique'), ('Three.js', 'Technique'), ('D3.js', 'Technique'),
('Chart.js', 'Technique'), ('Web Components', 'Technique'),
('Responsive Design', 'Technique'), ('Accessibility (a11y)', 'Technique'),

-- Infrastructure as Code
('Pulumi', 'DevOps'), ('AWS CloudFormation', 'DevOps'), ('AWS CDK', 'DevOps'),
('OpenTofu', 'DevOps'), ('Vagrant', 'DevOps'), ('Packer', 'DevOps'),

-- DevOps Tools (additional)
('Helm', 'DevOps'), ('ArgoCD', 'DevOps'), ('Prometheus', 'DevOps'),
('Grafana', 'DevOps'), ('SonarQube', 'DevOps'), ('ELK Stack', 'DevOps'),
('Datadog', 'DevOps'), ('New Relic', 'DevOps'), ('Snyk', 'DevOps'),
('Trivy', 'DevOps'), ('Vault', 'DevOps'), ('Consul', 'DevOps'),
('Istio', 'DevOps'), ('Linkerd', 'DevOps');
