// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextStep.Modules.Coaching.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextStep.Modules.Coaching.Infrastructure.Persistence.Migrations {
    [DbContext(typeof(CoachingDbContext))]
    [Migration("20260927175123_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("coaching")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextStep.Modules.Coaching.Domain.QuestionEntrainement", b =>
                {
                    b.Property<Guid>("IdQuestion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_question")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("CompanySpecific")
                        .HasColumnType("boolean")
                        .HasColumnName("company_specific");

                    b.Property<string>("ConseilReponse")
                        .HasColumnType("text")
                        .HasColumnName("conseil_reponse");

                    b.Property<string>("CorrectionIa")
                        .HasColumnType("text")
                        .HasColumnName("correction_ia");

                    b.Property<Guid>("IdSession")
                        .HasColumnType("uuid")
                        .HasColumnName("id_session");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.Property<string>("ReponseUtilisateur")
                        .HasColumnType("text")
                        .HasColumnName("reponse_utilisateur");

                    b.Property<int?>("ScoreReponse")
                        .HasColumnType("integer")
                        .HasColumnName("score_reponse");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("TexteQuestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texte_question");

                    b.Property<string>("TypeQuestion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type_question");

                    b.HasKey("IdQuestion");

                    b.HasIndex("IdSession")
                        .HasDatabaseName("idx_question_session");

                    b.ToTable("question_entrainement", "coaching");
                });

            modelBuilder.Entity("NextStep.Modules.Coaching.Domain.SessionCoaching", b =>
                {
                    b.Property<Guid>("IdSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_session")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("DateSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_session")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("duration_minutes");

                    b.Property<string>("FeedbackJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("feedback_json");

                    b.Property<string>("FocusAreas")
                        .HasColumnType("jsonb")
                        .HasColumnName("focus_areas");

                    b.Property<Guid?>("IdCandidature")
                        .HasColumnType("uuid")
                        .HasColumnName("id_candidature");

                    b.Property<Guid>("IdUtilisateur")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en")
                        .HasColumnName("language");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("offer")
                        .HasColumnName("mode");

                    b.Property<int?>("ScoreEntretien")
                        .HasColumnType("integer")
                        .HasColumnName("score_entretien");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("IdSession");

                    b.HasIndex("IdCandidature")
                        .HasDatabaseName("idx_session_candidature");

                    b.HasIndex("IdUtilisateur")
                        .HasDatabaseName("idx_session_user");

                    b.ToTable("session_coaching", "coaching");
                });

            modelBuilder.Entity("NextStep.Modules.Coaching.Domain.QuestionEntrainement", b =>
                {
                    b.HasOne("NextStep.Modules.Coaching.Domain.SessionCoaching", "Session")
                        .WithMany()
                        .HasForeignKey("IdSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });
#pragma warning restore 612, 618
        }
    }
}
