// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NextStep.Infrastructure.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415110002_RefactorOnboardingToProfileFlow")]
    partial class RefactorOnboardingToProfileFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextStep.Modules.Identity.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Coordonnees")
                        .HasColumnType("text")
                        .HasColumnName("coordonnees");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_inscription");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keycloak_id");

                    b.Property<string>("LienGithub")
                        .HasColumnType("text")
                        .HasColumnName("lien_github");

                    b.Property<string>("LienLinkedin")
                        .HasColumnType("text")
                        .HasColumnName("lien_linkedin");

                    b.Property<string>("LienPortfolio")
                        .HasColumnType("text")
                        .HasColumnName("lien_portfolio");

                    b.Property<string>("Niveau")
                        .HasColumnType("text")
                        .HasColumnName("niveau");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Objectif")
                        .HasColumnType("text")
                        .HasColumnName("objectif");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<string>("OnboardingData")
                        .HasColumnType("jsonb")
                        .HasColumnName("onboarding_data");

                    b.Property<int>("OnboardingStep")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_step");

                    b.Property<string>("Prenom")
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<int>("ProfileScore")
                        .HasColumnType("integer")
                        .HasColumnName("profile_score");

                    b.Property<string>("ResumeProfessionnel")
                        .HasColumnType("text")
                        .HasColumnName("resume_professionnel");

                    b.Property<string>("Secteur")
                        .HasColumnType("text")
                        .HasColumnName("secteur");

                    b.HasKey("Id");

                    b.ToTable("utilisateur");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Models.Competence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_competence");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<int>("Niveau")
                        .HasColumnType("integer")
                        .HasColumnName("niveau");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("TypeCompetence")
                        .HasColumnType("text")
                        .HasColumnName("type_competence");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.ToTable("competence");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Models.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_experience");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_fin");

                    b.Property<string>("Entreprise")
                        .HasColumnType("text")
                        .HasColumnName("entreprise");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("Missions")
                        .HasColumnType("text")
                        .HasColumnName("missions");

                    b.Property<string>("Poste")
                        .HasColumnType("text")
                        .HasColumnName("poste");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.ToTable("experience");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Models.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_formation");

                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("annee");

                    b.Property<string>("Diplome")
                        .HasColumnType("text")
                        .HasColumnName("diplome");

                    b.Property<string>("Etablissement")
                        .HasColumnType("text")
                        .HasColumnName("etablissement");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.ToTable("formation");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Models.Projet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_projet");

                    b.Property<DateTime?>("DateRealisation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_realisation");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("LienProjet")
                        .HasColumnType("text")
                        .HasColumnName("lien_projet");

                    b.Property<string>("TechnologiesUtilisees")
                        .HasColumnType("text")
                        .HasColumnName("technologies_utilisees");

                    b.Property<string>("TitreProjet")
                        .HasColumnType("text")
                        .HasColumnName("titre_projet");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.ToTable("projet");
                });
#pragma warning restore 612, 618
        }
    }
}
