// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextStep.data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextStep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextStep.Modules.Candidature.Models.Candidature", b =>
                {
                    b.Property<Guid>("IdCandidature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_candidature")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("FollowUpNeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("follow_up_needed");

                    b.Property<bool>("HasResponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_response");

                    b.Property<Guid>("IdOffre")
                        .HasColumnType("uuid")
                        .HasColumnName("id_offre");

                    b.Property<Guid>("IdUtilisateur")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.Property<bool>("InclureLettreMotivation")
                        .HasColumnType("boolean")
                        .HasColumnName("inclure_lettre_motivation");

                    b.Property<DateTime?>("LastCheckedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_checked_at_utc");

                    b.Property<DateTime?>("LastFollowUpAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_follow_up_at_utc");

                    b.Property<DateTime?>("LastResponseAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_response_at_utc");

                    b.Property<string>("LastResponseFrom")
                        .HasColumnType("text")
                        .HasColumnName("last_response_from");

                    b.Property<string>("LastResponseSnippet")
                        .HasColumnType("text")
                        .HasColumnName("last_response_snippet");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text")
                        .HasColumnName("recommended_action");

                    b.Property<double?>("ResponseClassifiedAtUtc")
                        .HasColumnType("double precision")
                        .HasColumnName("response_classified_at_utc");

                    b.Property<double?>("ResponseConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("response_confidence");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("EN_ATTENTE")
                        .HasColumnName("response_status");

                    b.Property<string>("ResponseSummary")
                        .HasColumnType("text")
                        .HasColumnName("response_summary");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("EN_ATTENTE")
                        .HasColumnName("statut");

                    b.HasKey("IdCandidature");

                    b.HasIndex("IdOffre");

                    b.ToTable("candidature", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Candidature.Models.DocumentGenere", b =>
                {
                    b.Property<Guid>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_document")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CheminPdfCv")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("chemin_pdf_cv");

                    b.Property<string>("CheminPdfLettre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("chemin_pdf_lettre");

                    b.Property<string>("CvContenuIaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("cv_contenu_ia_json");

                    b.Property<DateTime>("DateGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_generation")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IdCandidature")
                        .HasColumnType("uuid")
                        .HasColumnName("id_candidature");

                    b.Property<string>("LettreMotivContenuIa")
                        .HasColumnType("text")
                        .HasColumnName("lettre_motiv_contenu_ia");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("IdDocument");

                    b.HasIndex("IdCandidature")
                        .IsUnique();

                    b.ToTable("document_genere", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Cv.Models.CvHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bucket_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CvDataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("cv_data_json");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("template_name");

                    b.Property<string>("TemplateSlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template_slug");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_cv_history_user_created");

                    b.ToTable("cv_history", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Cv.Models.CvTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasDefaultValue("#FFFFFF")
                        .HasColumnName("background_color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string>("ExperienceLevels")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("experience_levels");

                    b.PrimitiveCollection<string>("Industries")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("industries");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Layout")
                        .HasColumnType("integer")
                        .HasColumnName("layout");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("style");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("cv_template", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Email.Models.EmailDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_email_draft")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corps");

                    b.Property<Guid>("CandidatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_candidature");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("application")
                        .HasColumnName("type_email");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("est_approuve");

                    b.Property<bool>("IsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("est_envoye");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("fr")
                        .HasColumnName("langue");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient_email");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_envoi");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("objet");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_modification");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId");

                    b.ToTable("email_draft", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Identity.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Coordonnees")
                        .HasColumnType("text")
                        .HasColumnName("coordonnees");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_inscription");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keycloak_id");

                    b.Property<string>("LienGithub")
                        .HasColumnType("text")
                        .HasColumnName("lien_github");

                    b.Property<string>("LienLinkedin")
                        .HasColumnType("text")
                        .HasColumnName("lien_linkedin");

                    b.Property<string>("LienPortfolio")
                        .HasColumnType("text")
                        .HasColumnName("lien_portfolio");

                    b.Property<string>("Niveau")
                        .HasColumnType("text")
                        .HasColumnName("niveau");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Objectif")
                        .HasColumnType("text")
                        .HasColumnName("objectif");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<string>("OnboardingData")
                        .HasColumnType("jsonb")
                        .HasColumnName("onboarding_data");

                    b.Property<int>("OnboardingStep")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_step");

                    b.Property<string>("Pays")
                        .HasColumnType("text")
                        .HasColumnName("pays");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Prenom")
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<int>("ProfileScore")
                        .HasColumnType("integer")
                        .HasColumnName("profile_score");

                    b.Property<string>("ResumeProfessionnel")
                        .HasColumnType("text")
                        .HasColumnName("resume_professionnel");

                    b.Property<string>("Secteur")
                        .HasColumnType("text")
                        .HasColumnName("secteur");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.Property<string>("TitrePoste")
                        .HasColumnType("text")
                        .HasColumnName("titre_poste");

                    b.Property<string>("TitresSections")
                        .HasColumnType("jsonb")
                        .HasColumnName("titres_sections");

                    b.Property<string>("Ville")
                        .HasColumnType("text")
                        .HasColumnName("ville");

                    b.HasKey("Id");

                    b.ToTable("utilisateur", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Offer.Models.OffreEmploi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AnalyseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("analyse_json");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TexteBrut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texte_brut");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("Id");

                    b.ToTable("offres_emploi", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Models.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_certification");

                    b.Property<DateTime?>("DateObtention")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_obtention");

                    b.Property<string>("IdCredential")
                        .HasColumnType("text")
                        .HasColumnName("id_credential");

                    b.Property<string>("Organisation")
                        .HasColumnType("text")
                        .HasColumnName("organisation");

                    b.Property<string>("Titre")
                        .HasColumnType("text")
                        .HasColumnName("titre");

                    b.Property<string>("UrlCredential")
                        .HasColumnType("text")
                        .HasColumnName("url_credential");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.ToTable("certification", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Models.Competence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_competence");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<int>("Niveau")
                        .HasColumnType("integer")
                        .HasColumnName("niveau");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("TypeCompetence")
                        .HasColumnType("text")
                        .HasColumnName("type_competence");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.ToTable("competence", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Models.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_experience");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_fin");

                    b.Property<string>("Entreprise")
                        .HasColumnType("text")
                        .HasColumnName("entreprise");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("Missions")
                        .HasColumnType("text")
                        .HasColumnName("missions");

                    b.Property<string>("Poste")
                        .HasColumnType("text")
                        .HasColumnName("poste");

                    b.PrimitiveCollection<string>("Taches")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("taches");

                    b.Property<string>("TypeContrat")
                        .HasColumnType("text")
                        .HasColumnName("type_contrat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Ville")
                        .HasColumnType("text")
                        .HasColumnName("ville");

                    b.HasKey("Id");

                    b.ToTable("experience", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Models.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_formation");

                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("annee");

                    b.Property<int?>("AnneeFin")
                        .HasColumnType("integer")
                        .HasColumnName("annee_fin");

                    b.Property<string>("Diplome")
                        .HasColumnType("text")
                        .HasColumnName("diplome");

                    b.Property<string>("Etablissement")
                        .HasColumnType("text")
                        .HasColumnName("etablissement");

                    b.Property<string>("Mention")
                        .HasColumnType("text")
                        .HasColumnName("mention");

                    b.Property<string>("Specialisation")
                        .HasColumnType("text")
                        .HasColumnName("specialisation");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Ville")
                        .HasColumnType("text")
                        .HasColumnName("ville");

                    b.HasKey("Id");

                    b.ToTable("formation", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Models.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_skill_keyword");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categorie");

                    b.Property<string>("Mot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mot");

                    b.HasKey("Id");

                    b.ToTable("skill_keyword", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Models.Projet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_projet");

                    b.Property<DateTime?>("DateRealisation")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_realisation");

                    b.Property<string>("DemoUrl")
                        .HasColumnType("text")
                        .HasColumnName("demo_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsUniversity")
                        .HasColumnType("boolean")
                        .HasColumnName("is_university");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("LienProjet")
                        .HasColumnType("text")
                        .HasColumnName("lien_projet");

                    b.PrimitiveCollection<string>("Taches")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("taches");

                    b.Property<string>("TechnologiesUtilisees")
                        .HasColumnType("text")
                        .HasColumnName("technologies_utilisees");

                    b.Property<string>("TitreProjet")
                        .HasColumnType("text")
                        .HasColumnName("titre_projet");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.ToTable("projet", "public");
                });

            modelBuilder.Entity("NextStep.Modules.Candidature.Models.Candidature", b =>
                {
                    b.HasOne("NextStep.Modules.Offer.Models.OffreEmploi", "Offre")
                        .WithMany()
                        .HasForeignKey("IdOffre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("NextStep.Modules.Candidature.Models.DocumentGenere", b =>
                {
                    b.HasOne("NextStep.Modules.Candidature.Models.Candidature", "Candidature")
                        .WithOne()
                        .HasForeignKey("NextStep.Modules.Candidature.Models.DocumentGenere", "IdCandidature")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("NextStep.Modules.Email.Models.EmailDraft", b =>
                {
                    b.HasOne("NextStep.Modules.Candidature.Models.Candidature", "Candidature")
                        .WithMany("EmailDrafts")
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("NextStep.Modules.Candidature.Models.Candidature", b =>
                {
                    b.Navigation("EmailDrafts");
                });
#pragma warning restore 612, 618
        }
    }
}
