# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # VM 1: App Node
  config.vm.define "app" do |app|
    app.vm.hostname = "nextstep-app"
    app.vm.network "private_network", ip: "192.168.99.10"
    
    app.vm.provider "vmware_desktop" do |v|
      v.gui = true
      v.memory = 4096
      v.cpus = 2
    end
  end

  # VM 2: DB Node
  config.vm.define "db" do |db|
    db.vm.hostname = "nextstep-db"
    db.vm.network "private_network", ip: "192.168.99.11"
    
    db.vm.provider "vmware_desktop" do |v|
      v.gui = true
      v.memory = 2048
      v.cpus = 1
    end
  end
end
