Vagrant.configure("2") do |config|
  # Image Ubuntu Server légère
  config.vm.box = "bento/ubuntu-24.04"

  # ==========================================
  # VM 1 : APPLICATION (backend + frontend + nginx)
  # ==========================================
  config.vm.define "app-server" do |app|
    app.vm.hostname = "app-server"
    # Changement de l'IP pour correspondre à ton VMnet8 (192.168.152.x)
    app.vm.network "private_network", ip: "192.168.152.11"
    
    app.vm.provider "vmware_desktop" do |v|
      v.cpus = 2
      v.memory = 2048
      v.gui = true
      v.vmx["displayname"] = "App-Server"
    end
  end

  # ==========================================
  # VM 2 : DATA + MONITORING (Postgres + Prometheus + Grafana)
  # ==========================================
  config.vm.define "data-monitoring-server" do |db|
    db.vm.hostname = "data-monitoring-server"
    # Changement de l'IP pour correspondre à ton VMnet8 (192.168.152.x)
    db.vm.network "private_network", ip: "192.168.152.12"
    
    db.vm.provider "vmware_desktop" do |v|
      v.cpus = 2
      v.memory = 2048
      v.gui = true
      v.vmx["displayname"] = "Data-Monitoring-Server"
    end
  end
end