/** The CV being edited in the resume editor (generated by the AI, then edited by the user). */
export interface Candidate {
  name: string;
  email: string;
  phone: string;
  location: string;
  title: string;
  photoUrl: string | null;
  linkedIn: string | null;
  gitHub: string | null;
  portfolio: string | null;
}

export interface Experience {
  role: string;
  company: string;
  start: string;
  end: string;
  bullets: string[];
  relevance?: string;
  keywords?: string[];
}

export interface Education {
  degree: string;
  institution: string;
  year: string;
  startYear?: string;
  endYear?: string;
}

export interface Skill {
  name: string;
  level: number;
  isMatched: boolean;
  isHighlighted?: boolean;
  category?: string;
  typeCompetence?: string;
}

export interface Project {
  title: string;
  description?: string;
  technologies?: string[];
  dateRealisation?: string;
  bullets: string[];
  relevance?: string;
  keywords?: string[];
}

export interface Activity {
  title: string;
  role?: string | null;
  description?: string | null;
  startDate?: string | null;
  endDate?: string | null;
}

export interface CvGeneratedSchema {
  candidate: Candidate;
  summary: string;
  experience: Experience[];
  education: Education[];
  skills: Skill[];
  projects: Project[];
  certifications: string[];
  languages: string[];
  activities: Activity[];
  accomplishments: string[];
  atsScore: number;
  matchingScore: number;
  atsCoveragePct: number;
}

export interface CvSectionItem {
  primaryText: string;
  secondaryText?: string;
  startDate?: string | null;
  endDate?: string | null;
  location?: string | null;
  description?: string | null;
  level?: number | null;
  isMatched?: boolean;
  bullets: string[];
}

export interface CvSection {
  id: string;
  type: string;
  title: string;
  placement: 'main' | 'sidebar';
  isVisible: boolean;
  order: number;
  text?: string | null;
  items: CvSectionItem[];
}
