// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextStep.Modules.Profile.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextStep.Modules.Profile.Infrastructure.Persistence.Migrations {
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20260927175831_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profile")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_certification");

                    b.Property<DateTime?>("DateObtention")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_obtention");

                    b.Property<string>("IdCredential")
                        .HasColumnType("text")
                        .HasColumnName("id_credential");

                    b.Property<string>("Organisation")
                        .HasColumnType("text")
                        .HasColumnName("organisation");

                    b.Property<string>("Titre")
                        .HasColumnType("text")
                        .HasColumnName("titre");

                    b.Property<string>("UrlCredential")
                        .HasColumnType("text")
                        .HasColumnName("url_credential");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("certification", "profile");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Competence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_competence");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<int>("Niveau")
                        .HasColumnType("integer")
                        .HasColumnName("niveau");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("TypeCompetence")
                        .HasColumnType("text")
                        .HasColumnName("type_competence");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("competence", "profile");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_experience");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_fin");

                    b.Property<string>("Entreprise")
                        .HasColumnType("text")
                        .HasColumnName("entreprise");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("Missions")
                        .HasColumnType("text")
                        .HasColumnName("missions");

                    b.Property<string>("Poste")
                        .HasColumnType("text")
                        .HasColumnName("poste");

                    b.PrimitiveCollection<string>("Taches")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("taches")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("TypeContrat")
                        .HasColumnType("text")
                        .HasColumnName("type_contrat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Ville")
                        .HasColumnType("text")
                        .HasColumnName("ville");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("experience", "profile");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_formation");

                    b.Property<int>("Annee")
                        .HasColumnType("integer")
                        .HasColumnName("annee");

                    b.Property<int?>("AnneeFin")
                        .HasColumnType("integer")
                        .HasColumnName("annee_fin");

                    b.Property<string>("Diplome")
                        .HasColumnType("text")
                        .HasColumnName("diplome");

                    b.Property<string>("Etablissement")
                        .HasColumnType("text")
                        .HasColumnName("etablissement");

                    b.Property<string>("Mention")
                        .HasColumnType("text")
                        .HasColumnName("mention");

                    b.Property<string>("Specialisation")
                        .HasColumnType("text")
                        .HasColumnName("specialisation");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Ville")
                        .HasColumnType("text")
                        .HasColumnName("ville");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("formation", "profile");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_skill_keyword")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Technique")
                        .HasColumnName("categorie");

                    b.Property<string>("Mot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mot");

                    b.HasKey("Id");

                    b.ToTable("skill_keyword", "profile");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Projet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_projet");

                    b.Property<DateTime?>("DateRealisation")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_realisation");

                    b.Property<string>("DemoUrl")
                        .HasColumnType("text")
                        .HasColumnName("demo_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsUniversity")
                        .HasColumnType("boolean")
                        .HasColumnName("is_university");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("LienProjet")
                        .HasColumnType("text")
                        .HasColumnName("lien_projet");

                    b.PrimitiveCollection<string>("Taches")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("taches")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("TechnologiesUtilisees")
                        .HasColumnType("text")
                        .HasColumnName("technologies_utilisees");

                    b.Property<string>("TitreProjet")
                        .HasColumnType("text")
                        .HasColumnName("titre_projet");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("projet", "profile");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Coordonnees")
                        .HasColumnType("text")
                        .HasColumnName("coordonnees");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_inscription");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keycloak_id");

                    b.Property<string>("LienGithub")
                        .HasColumnType("text")
                        .HasColumnName("lien_github");

                    b.Property<string>("LienLinkedin")
                        .HasColumnType("text")
                        .HasColumnName("lien_linkedin");

                    b.Property<string>("LienPortfolio")
                        .HasColumnType("text")
                        .HasColumnName("lien_portfolio");

                    b.Property<string>("Niveau")
                        .HasColumnType("text")
                        .HasColumnName("niveau");

                    b.Property<string>("Nom")
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Objectif")
                        .HasColumnType("text")
                        .HasColumnName("objectif");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<string>("OnboardingData")
                        .HasColumnType("jsonb")
                        .HasColumnName("onboarding_data");

                    b.Property<int>("OnboardingStep")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_step");

                    b.Property<string>("Pays")
                        .HasColumnType("text")
                        .HasColumnName("pays");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Prenom")
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<bool>("ProfileCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("profile_completed");

                    b.Property<int>("ProfileScore")
                        .HasColumnType("integer")
                        .HasColumnName("profile_score");

                    b.Property<string>("ResumeProfessionnel")
                        .HasColumnType("text")
                        .HasColumnName("resume_professionnel");

                    b.Property<string>("Secteur")
                        .HasColumnType("text")
                        .HasColumnName("secteur");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.Property<string>("TitrePoste")
                        .HasColumnType("text")
                        .HasColumnName("titre_poste");

                    b.Property<string>("TitresSections")
                        .HasColumnType("jsonb")
                        .HasColumnName("titres_sections");

                    b.Property<string>("Ville")
                        .HasColumnType("text")
                        .HasColumnName("ville");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_utilisateur_email");

                    b.HasIndex("KeycloakId")
                        .HasDatabaseName("idx_utilisateur_keycloak_id");

                    b.ToTable("utilisateur", "profile");
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Certification", b =>
                {
                    b.HasOne("NextStep.Modules.Profile.Domain.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Competence", b =>
                {
                    b.HasOne("NextStep.Modules.Profile.Domain.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Experience", b =>
                {
                    b.HasOne("NextStep.Modules.Profile.Domain.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Formation", b =>
                {
                    b.HasOne("NextStep.Modules.Profile.Domain.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NextStep.Modules.Profile.Domain.Projet", b =>
                {
                    b.HasOne("NextStep.Modules.Profile.Domain.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
