// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextStep.Modules.Sourcing.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextStep.Modules.Sourcing.Infrastructure.Persistence.Migrations {
    [DbContext(typeof(SourcingDbContext))]
    partial class SourcingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sourcing")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextStep.Modules.Sourcing.Domain.ScrapeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContractTypesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("contract_types_json");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("errors_json");

                    b.Property<string>("Keywords")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("keywords");

                    b.Property<int>("Limit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("limit_value");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<string>("PostedWindow")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("posted_window");

                    b.Property<string>("ProvidersJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("providers_json");

                    b.Property<int>("ResultCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("result_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("warnings_json");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_scrape_session_user_created");

                    b.ToTable("scrape_session", "sourcing");
                });

            modelBuilder.Entity("NextStep.Modules.Sourcing.Domain.SourcedOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Company")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("employment_type");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("external_url");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("first_seen_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_saved");

                    b.Property<bool>("IsShortlisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_shortlisted");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_seen_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<string>("MatchedItTermsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("matched_it_terms_json");

                    b.Property<string>("NormalizedContractType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("normalized_contract_type");

                    b.Property<string>("PostedAtText")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("posted_at_text");

                    b.Property<string>("PostedWindow")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("posted_window");

                    b.Property<Guid?>("PromotedOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("promoted_offer_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderJobId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_job_id");

                    b.Property<string>("RawContractType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("raw_contract_type");

                    b.Property<DateTime>("ScrapedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scraped_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SeniorityLevel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("seniority_level");

                    b.Property<string>("SourceQueryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("source_query_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DedupeKey")
                        .HasDatabaseName("ix_sourced_offer_user_dedupe");

                    b.HasIndex("UserId", "Provider", "ProviderJobId")
                        .HasDatabaseName("ix_sourced_offer_user_provider_job");

                    b.ToTable("sourced_offer", "sourcing");
                });
#pragma warning restore 612, 618
        }
    }
}
