[app]
vm1 ansible_host=192.168.77.10 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/vm1/vmware_desktop/private_key

[data]
vm2 ansible_host=192.168.77.11 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/vm2/vmware_desktop/private_key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
