# ============================================================
# Ansible Inventory — NextStep Local Infrastructure
# 2 VMs Vagrant sur réseau privé 192.168.99.0/24
# ============================================================

[app]
nextstep-app ansible_host=192.168.99.10 ansible_user=vagrant ansible_ssh_private_key_file=../.vagrant/machines/app/vmware_desktop/private_key

[db]
nextstep-db ansible_host=192.168.99.11 ansible_user=vagrant ansible_ssh_private_key_file=../.vagrant/machines/db/vmware_desktop/private_key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
