[webservers]
app-server ansible_host=192.168.152.11

[databases]
data-monitoring-server ansible_host=192.168.152.12

[all:vars]
# Configuration SSH pour Vagrant (environnement local uniquement)
ansible_user=vagrant
ansible_password=vagrant
# Demander à Ansible de ne pas vérifier ou vérifier strictement les clés SSH locales
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
