---
- name: Installer Docker et déployer Nginx
  hosts: all
  become: yes # Exécuter en tant que root
  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer les dépendances pour Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Installer Docker
      apt:
        name: docker.io
        state: present

    - name: S'assurer que Docker est démarré et activé
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Nettoyer l'ancien container Nginx (si existant)
      docker_container:
        name: my-nginx
        state: absent

    - name: Télécharger l'image Apache et créer le container
      docker_container:
        name: my-apache
        image: httpd:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
