// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextStep.Modules.Applications.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextStep.Modules.Applications.Infrastructure.Persistence.Migrations {
    [DbContext(typeof(ApplicationsDbContext))]
    [Migration("20260927174930_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("applications")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextStep.Modules.Applications.Domain.Candidature", b =>
                {
                    b.Property<Guid>("IdCandidature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_candidature")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("application_date")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("AppliedManually")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("applied_manually");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("EMAIL")
                        .HasColumnName("channel");

                    b.Property<string>("ChannelContact")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("channel_contact");

                    b.Property<string>("ChannelUrl")
                        .HasColumnType("text")
                        .HasColumnName("channel_url");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("FollowUpNeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("follow_up_needed");

                    b.Property<bool>("HasResponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_response");

                    b.Property<Guid?>("IdOffre")
                        .HasColumnType("uuid")
                        .HasColumnName("id_offre");

                    b.Property<Guid>("IdUtilisateur")
                        .HasColumnType("uuid")
                        .HasColumnName("id_utilisateur");

                    b.Property<bool>("InclureLettreMotivation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("inclure_lettre_motivation");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("AUTO")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastCheckedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_checked_at_utc");

                    b.Property<DateTime?>("LastFollowUpAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_follow_up_at_utc");

                    b.Property<DateTime?>("LastResponseAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_response_at_utc");

                    b.Property<string>("LastResponseFrom")
                        .HasColumnType("text")
                        .HasColumnName("last_response_from");

                    b.Property<string>("LastResponseSnippet")
                        .HasColumnType("text")
                        .HasColumnName("last_response_snippet");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OfferSource")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("offer_source");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text")
                        .HasColumnName("recommended_action");

                    b.Property<DateTime?>("ResponseClassifiedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("response_classified_at_utc");

                    b.Property<double?>("ResponseConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("response_confidence");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("EN_ATTENTE")
                        .HasColumnName("response_status");

                    b.Property<string>("ResponseSummary")
                        .HasColumnType("text")
                        .HasColumnName("response_summary");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("ENVOYE")
                        .HasColumnName("statut");

                    b.HasKey("IdCandidature");

                    b.HasIndex("IdOffre")
                        .HasDatabaseName("ix_candidature_id_offre");

                    b.HasIndex("IdUtilisateur")
                        .HasDatabaseName("ix_candidature_id_utilisateur");

                    b.ToTable("candidature", "applications");
                });

            modelBuilder.Entity("NextStep.Modules.Applications.Domain.CandidatureNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("user")
                        .HasColumnName("auteur");

                    b.Property<Guid>("CandidatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_candidature");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId")
                        .HasDatabaseName("ix_candidature_note_candidature");

                    b.ToTable("candidature_note", "applications");
                });

            modelBuilder.Entity("NextStep.Modules.Applications.Domain.CandidatureStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AncienStatut")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ancien_statut");

                    b.Property<Guid>("CandidatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_candidature");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("NouveauStatut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nouveau_statut");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("user")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId")
                        .HasDatabaseName("ix_candidature_status_history_candidature");

                    b.ToTable("candidature_status_history", "applications");
                });

            modelBuilder.Entity("NextStep.Modules.Applications.Domain.DocumentGenere", b =>
                {
                    b.Property<Guid>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_document")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CheminPdfCv")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("chemin_pdf_cv");

                    b.Property<string>("CheminPdfLettre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("chemin_pdf_lettre");

                    b.Property<string>("CvContenuIaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("cv_contenu_ia_json");

                    b.Property<DateTime>("DateGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_generation")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IdCandidature")
                        .HasColumnType("uuid")
                        .HasColumnName("id_candidature");

                    b.Property<string>("LettreMotivContenuIa")
                        .HasColumnType("text")
                        .HasColumnName("lettre_motiv_contenu_ia");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("IdDocument");

                    b.HasIndex("IdCandidature")
                        .IsUnique();

                    b.ToTable("document_genere", "applications");
                });

            modelBuilder.Entity("NextStep.Modules.Applications.Domain.OffreEmploi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AnalyseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("analyse_json");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TexteBrut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texte_brut");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .HasDatabaseName("ix_offres_emploi_utilisateur_id");

                    b.ToTable("offres_emploi", "applications");
                });

            modelBuilder.Entity("NextStep.Modules.Applications.Domain.Candidature", b =>
                {
                    b.HasOne("NextStep.Modules.Applications.Domain.OffreEmploi", "Offre")
                        .WithMany()
                        .HasForeignKey("IdOffre")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("NextStep.Modules.Applications.Domain.CandidatureNote", b =>
                {
                    b.HasOne("NextStep.Modules.Applications.Domain.Candidature", "Candidature")
                        .WithMany("CandidatureNotes")
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("NextStep.Modules.Applications.Domain.CandidatureStatusHistory", b =>
                {
                    b.HasOne("NextStep.Modules.Applications.Domain.Candidature", "Candidature")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("NextStep.Modules.Applications.Domain.DocumentGenere", b =>
                {
                    b.HasOne("NextStep.Modules.Applications.Domain.Candidature", "Candidature")
                        .WithOne()
                        .HasForeignKey("NextStep.Modules.Applications.Domain.DocumentGenere", "IdCandidature")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("NextStep.Modules.Applications.Domain.Candidature", b =>
                {
                    b.Navigation("CandidatureNotes");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
